### ISSUE TITLE
It is mandatory To Have GLONASS Frequency Table? 

### ISSUE THREAD

**Issue by Waley04** [YizeZhang/Net_Diff#9]
Greetings,

Thanks for developing Net_Diff Software. 

I have the following issues:

1. It is mandatory to have a **GLONASS Frequency and Leap seconds table** even when processing other satellite systems (**other than GLONASS**)? 
2. I thought this could be applicable when processing GLONASS-only or GLONASS + any other constellation. 

It could be better if you made the  **GLONASS frequency and Leap seconds** inactive when processing the other constellations. 

Thanks and looking forward to your response.

Best wishes,

Waley.

**Comment by YizeZhang** [comment]
Thank you for your comment.

Yes, the GLONASS frequency is only valid when GLONASS system is used. However, the leap second information is also required when calculating the positioning of the Sun and Moon, the tidal correction since they need the UTC as input.
So I still set the GLOFre.txt  as a mandatory input in data processing. You can find the this file in the Input folder.

Best regards,

Yize Zhang

**Comment by Waley04** [comment]
Many thanks @YizeZhang for the technical support.
